#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_GOOGLE_include_directive : enable

// USE_10BIT selects the output image format.

#ifdef USE_10BIT
layout (set = 0, binding = 2, rgb10_a2) uniform writeonly image2D output_image;
#else
layout (set = 0, binding = 2, rgba8) uniform writeonly image2D output_image;
#endif

#include "screen_effects.inc"
