#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_KHR_shader_subgroup_shuffle : enable

layout(set = 0, binding = 0) uniform sampler2D input_tex;
layout(set = 0, binding = 1, rgb10_a2) uniform writeonly image2D output_image;

#define SCALING
#define USE_SUBGROUP_OPS
#include "screen_effects.inc"
