// MIT License
//
// Copyright (c) 2016-2021 Intel Corporation
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#version 450
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_control_flow_attributes : require
layout (local_size_x = 8, local_size_y = 8) in;
layout (set = 0, binding = 0) uniform sampler2D world_depth;
layout (set = 1, binding = 0) uniform sampler2D entity_depth;
layout (r32ui, set = 2, binding = 0) uniform writeonly uimage2D out_working_ao_term;
layout (r32f, set = 3, binding = 0) uniform writeonly image2D out_working_edges;
#include "gtao.inc"

uint hilbert_index (uint pos_x, uint pos_y)
{
	uint index = 0U;
	// Keep the Hilbert traversal unrolled: the NVIDIA compiler otherwise miscompiles it in the full AO shader.
	[[unroll]] for (uint cur_level = (1U << 6U) / 2U; cur_level > 0U; cur_level /= 2U)
	{
		uint region_x = uint ((pos_x & cur_level) > 0U);
		uint region_y = uint ((pos_y & cur_level) > 0U);
		index += cur_level * cur_level * ((3U * region_x) ^ region_y);
		if (region_y == 0U)
		{
			if (region_x == 1U)
			{
				pos_x = ((1U << 6U) - 1U) - pos_x;
				pos_y = ((1U << 6U) - 1U) - pos_y;
			}

			uint temp = pos_x;
			pos_x = pos_y;
			pos_y = temp;
		}
	}
	return index;
}

vec3 compute_viewspace_position (vec2 screen_pos, float viewspace_depth)
{
	vec3 ret;
	ret.xy = (pc.viewport.zw * screen_pos.xy + pc.projection.xy) * viewspace_depth;
	ret.z = viewspace_depth;
	return ret;
}

vec4 calculate_edges (float center_z, float left_z, float right_z, float top_z, float bottom_z)
{
	vec4 edges_lrtb = vec4 (left_z, right_z, top_z, bottom_z) - center_z;

	float slope_lr = (edges_lrtb.y - edges_lrtb.x) * 0.5;
	float slope_tb = (edges_lrtb.w - edges_lrtb.z) * 0.5;
	vec4  edges_lrtb_slope_adjusted = edges_lrtb + vec4 (slope_lr, -slope_lr, slope_tb, -slope_tb);
	edges_lrtb = min (abs (edges_lrtb), abs (edges_lrtb_slope_adjusted));
	return clamp (1.25 - edges_lrtb / (center_z * 0.011), 0.0, 1.0);
}

float pack_edges (vec4 edges_lrtb)
{
	edges_lrtb = round (clamp (edges_lrtb, 0.0, 1.0) * 2.9);
	return dot (edges_lrtb, vec4 (64.0 / 255.0, 16.0 / 255.0, 4.0 / 255.0, 1.0 / 255.0));
}

vec3 calculate_normal (vec4 edges_lrtb, vec3 pix_center_pos, vec3 pix_l_pos, vec3 pix_r_pos, vec3 pix_t_pos, vec3 pix_b_pos)
{
	vec4 accepted_normals =
		clamp (vec4 (edges_lrtb.x * edges_lrtb.z, edges_lrtb.z * edges_lrtb.y, edges_lrtb.y * edges_lrtb.w, edges_lrtb.w * edges_lrtb.x) + 0.01, 0.0, 1.0);

	pix_l_pos = normalize (pix_l_pos - pix_center_pos);
	pix_r_pos = normalize (pix_r_pos - pix_center_pos);
	pix_t_pos = normalize (pix_t_pos - pix_center_pos);
	pix_b_pos = normalize (pix_b_pos - pix_center_pos);

	vec3 pixel_normal = accepted_normals.x * cross (pix_l_pos, pix_t_pos) + accepted_normals.y * cross (pix_t_pos, pix_r_pos) +
						accepted_normals.z * cross (pix_r_pos, pix_b_pos) + accepted_normals.w * cross (pix_b_pos, pix_l_pos);
	pixel_normal = normalize (pixel_normal);

	return pixel_normal;
}

float fast_sqrt (float x)
{
	return intBitsToFloat (0x1fbd1df5 + (floatBitsToInt (x) >> 1));
}

float fast_acos (float in_x)
{
	float pi = 3.141593;
	float half_pi = 1.570796;
	float x = abs (in_x);
	float res = -0.156583 * x + half_pi;
	res *= fast_sqrt (1.0 - x);
	return (in_x >= 0) ? res : pi - res;
}

void main ()
{
	uvec2		   pixel = gl_GlobalInvocationID.xy;
	gtao_constants c = get_gtao_constants ();
	if (any (greaterThanEqual (pixel, uvec2 (c.viewport_size))))
		return;
	if (texelFetch (world_depth, ivec2 (pixel), 0).x >= 1e8)
	{
		imageStore (out_working_ao_term, ivec2 (pixel), uvec4 (170));
		imageStore (out_working_edges, ivec2 (pixel), vec4 (0));
		return;
	}
	uint		index = hilbert_index (pixel.x, pixel.y);
	vec2		noise = fract (0.5 + float (index) * vec2 (0.75487766624669276, 0.56984029099805326));
	const float slice_count = 3.0;
	const float steps_per_slice = 3.0;

	vec2 normalized_screen_pos = (pixel + vec2 (0.5)) * c.viewport_pixel_size;

	vec4 values_ul = textureGather (world_depth, pixel * c.viewport_pixel_size, 0);
	vec4 values_br = textureGatherOffset (world_depth, pixel * c.viewport_pixel_size, ivec2 (1, 1), 0);

	float viewspace_z = values_ul.y;

	float pix_lz = values_ul.x;
	float pix_tz = values_ul.z;
	float pix_rz = values_br.z;
	float pix_bz = values_br.x;

	vec4 edges_lrtb = calculate_edges (viewspace_z, pix_lz, pix_rz, pix_tz, pix_bz);
	imageStore (out_working_edges, ivec2 (pixel), vec4 (pack_edges (edges_lrtb)));

	vec3 center = compute_viewspace_position (normalized_screen_pos, viewspace_z);
	vec3 left = compute_viewspace_position (normalized_screen_pos + vec2 (-1, 0) * c.viewport_pixel_size, pix_lz);
	vec3 right = compute_viewspace_position (normalized_screen_pos + vec2 (1, 0) * c.viewport_pixel_size, pix_rz);
	vec3 top = compute_viewspace_position (normalized_screen_pos + vec2 (0, -1) * c.viewport_pixel_size, pix_tz);
	vec3 bottom = compute_viewspace_position (normalized_screen_pos + vec2 (0, 1) * c.viewport_pixel_size, pix_bz);
	vec3 viewspace_normal = calculate_normal (edges_lrtb, center, left, right, top, bottom);

	viewspace_z *= 0.99999;

	vec3 pix_center_pos = compute_viewspace_position (normalized_screen_pos, viewspace_z);
	vec3 view_vec = normalize (-pix_center_pos);

	float effect_radius = c.effect_radius * 1.457;
	float sample_distribution_power = 2.0;
	float falloff_range = 0.615 * effect_radius;

	float falloff_from = effect_radius * (1.0 - c.effect_falloff_range);

	float falloff_mul = -1.0 / (falloff_range);
	float falloff_add = falloff_from / (falloff_range) + 1.0;

	float world_visibility = 0;
	float scene_visibility = 0;

	float noise_slice = noise.x;
	float noise_sample = noise.y;

	float pixel_too_close_threshold = 1.3;

	vec2 pixel_dir_rb_viewspace_size_at_center_z = viewspace_z.xx * c.ndc_to_view_mul_x_pixel_size;

	float screenspace_radius = effect_radius / pixel_dir_rb_viewspace_size_at_center_z.x;

	float small_radius_fade = clamp ((10 - screenspace_radius) / 100, 0.0, 1.0) * 0.5;
	world_visibility += small_radius_fade;
	scene_visibility += small_radius_fade;

	float min_s = pixel_too_close_threshold / screenspace_radius;

	for (float slice = 0; slice < slice_count; slice++)
	{
		float slice_k = (slice + noise_slice) / slice_count;

		float phi = slice_k * (3.1415926535897932384626433832795);
		float cos_phi = cos (phi);
		float sin_phi = sin (phi);
		vec2  omega = vec2 (cos_phi, -sin_phi);

		omega *= screenspace_radius;

		vec3 direction_vec = vec3 (cos_phi, sin_phi, 0);

		vec3 ortho_direction_vec = direction_vec - (dot (direction_vec, view_vec) * view_vec);

		vec3 axis_vec = normalize (cross (ortho_direction_vec, view_vec));

		vec3 projected_normal_vec = viewspace_normal - axis_vec * dot (viewspace_normal, axis_vec);

		float sign_norm = sign (dot (ortho_direction_vec, projected_normal_vec));

		float projected_normal_vec_length = length (projected_normal_vec);
		float cos_norm = clamp (dot (projected_normal_vec, view_vec) / projected_normal_vec_length, 0.0, 1.0);

		float n = sign_norm * fast_acos (cos_norm);

		float low_horizon_cos0 = cos (n + (1.5707963267948966192313216916398));
		float low_horizon_cos1 = cos (n - (1.5707963267948966192313216916398));

		float world_horizon_cos0 = low_horizon_cos0;
		float world_horizon_cos1 = low_horizon_cos1;
		float scene_horizon_cos0 = low_horizon_cos0;
		float scene_horizon_cos1 = low_horizon_cos1;

		for (float step = 0; step < steps_per_slice; step++)
		{
			float step_base_noise = (slice + step * steps_per_slice) * 0.6180339887498948482;
			float step_noise = fract (noise_sample + step_base_noise);

			float s = (step + step_noise) / (steps_per_slice);

			s = pow (s, sample_distribution_power);

			s += min_s;

			vec2 sample_offset = s * omega;

			float sample_offset_length = length (sample_offset);

			float mip_level = clamp (log2 (sample_offset_length) - c.depth_mip_sampling_offset, 0.0, 5.0);

			sample_offset = round (sample_offset) * c.viewport_pixel_size;

			vec2 sample_screen_pos0 = normalized_screen_pos + sample_offset;
			vec2 sample_depth0 = textureLod (entity_depth, sample_screen_pos0, mip_level).xy;
			vec3 world_sample_pos0 = compute_viewspace_position (sample_screen_pos0, sample_depth0.x);
			vec3 scene_sample_pos0 = compute_viewspace_position (sample_screen_pos0, sample_depth0.y);

			vec2 sample_screen_pos1 = normalized_screen_pos - sample_offset;
			vec2 sample_depth1 = textureLod (entity_depth, sample_screen_pos1, mip_level).xy;
			vec3 world_sample_pos1 = compute_viewspace_position (sample_screen_pos1, sample_depth1.x);
			vec3 scene_sample_pos1 = compute_viewspace_position (sample_screen_pos1, sample_depth1.y);

			vec3  world_sample_delta0 = world_sample_pos0 - pix_center_pos;
			vec3  world_sample_delta1 = world_sample_pos1 - pix_center_pos;
			vec3  scene_sample_delta0 = scene_sample_pos0 - pix_center_pos;
			vec3  scene_sample_delta1 = scene_sample_pos1 - pix_center_pos;
			float world_sample_dist0 = length (world_sample_delta0);
			float world_sample_dist1 = length (world_sample_delta1);
			float scene_sample_dist0 = length (scene_sample_delta0);
			float scene_sample_dist1 = length (scene_sample_delta1);

			float world_weight0 = clamp (world_sample_dist0 * falloff_mul + falloff_add, 0.0, 1.0);
			float world_weight1 = clamp (world_sample_dist1 * falloff_mul + falloff_add, 0.0, 1.0);
			float scene_weight0 = clamp (scene_sample_dist0 * falloff_mul + falloff_add, 0.0, 1.0);
			float scene_weight1 = clamp (scene_sample_dist1 * falloff_mul + falloff_add, 0.0, 1.0);
			bool  in_bounds0 = all (greaterThanEqual (sample_screen_pos0, vec2 (0))) && all (lessThanEqual (sample_screen_pos0, vec2 (1)));
			bool  in_bounds1 = all (greaterThanEqual (sample_screen_pos1, vec2 (0))) && all (lessThanEqual (sample_screen_pos1, vec2 (1)));
			world_weight0 *= sample_depth0.x < 1e8 && in_bounds0 ? 1 : 0;
			world_weight1 *= sample_depth1.x < 1e8 && in_bounds1 ? 1 : 0;
			scene_weight0 *= sample_depth0.y < 1e8 && in_bounds0 ? 1 : 0;
			scene_weight1 *= sample_depth1.y < 1e8 && in_bounds1 ? 1 : 0;

			float world_shc0 = mix (low_horizon_cos0, dot (world_sample_delta0 / world_sample_dist0, view_vec), world_weight0);
			float world_shc1 = mix (low_horizon_cos1, dot (world_sample_delta1 / world_sample_dist1, view_vec), world_weight1);
			float scene_shc0 = mix (low_horizon_cos0, dot (scene_sample_delta0 / scene_sample_dist0, view_vec), scene_weight0);
			float scene_shc1 = mix (low_horizon_cos1, dot (scene_sample_delta1 / scene_sample_dist1, view_vec), scene_weight1);

			world_horizon_cos0 = max (world_horizon_cos0, world_shc0);
			world_horizon_cos1 = max (world_horizon_cos1, world_shc1);
			scene_horizon_cos0 = max (scene_horizon_cos0, scene_shc0);
			scene_horizon_cos1 = max (scene_horizon_cos1, scene_shc1);
		}

		projected_normal_vec_length = mix (projected_normal_vec_length, 1, 0.05);

		float world_h0 = -fast_acos (world_horizon_cos1);
		float world_h1 = fast_acos (world_horizon_cos0);
		float scene_h0 = -fast_acos (scene_horizon_cos1);
		float scene_h1 = fast_acos (scene_horizon_cos0);

		float world_iarc0 = (cos_norm + 2.0 * world_h0 * sin (n) - cos (2.0 * world_h0 - n)) / 4.0;
		float world_iarc1 = (cos_norm + 2.0 * world_h1 * sin (n) - cos (2.0 * world_h1 - n)) / 4.0;
		float scene_iarc0 = (cos_norm + 2.0 * scene_h0 * sin (n) - cos (2.0 * scene_h0 - n)) / 4.0;
		float scene_iarc1 = (cos_norm + 2.0 * scene_h1 * sin (n) - cos (2.0 * scene_h1 - n)) / 4.0;
		world_visibility += projected_normal_vec_length * (world_iarc0 + world_iarc1);
		scene_visibility += projected_normal_vec_length * (scene_iarc0 + scene_iarc1);
	}
	// Divide out world-only occlusion so only the entities' additional occlusion remains.
	float visibility = clamp (scene_visibility / max (world_visibility, 1e-5), 0.0, 1.0);
	visibility = pow (visibility, c.final_value_power);
	visibility = max (0.03, visibility);

	visibility = clamp (visibility / 1.5, 0.0, 1.0);
	imageStore (out_working_ao_term, ivec2 (pixel), uvec4 (uint (visibility * 255.0 + 0.5)));
}
