#version 460
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_samplerless_texture_functions : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_ray_query : enable
// #define DEBUG
#ifdef DEBUG
#extension GL_EXT_debug_printf : enable
#endif

#define RAY_QUERIES

layout (set = 0, binding = 0, rgba8) uniform writeonly image2D output_image;

#include "update_lightmap.inc"
