/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.30.7-0-g9519b9916 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.30.7-0-g9519b9916"
#endif
#define SDL_REVISION_NUMBER 0
