name: Linux CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    - name: Determine version
      id: version
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "version=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
        else
          echo "version=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"
        fi
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build Docker image
      uses: docker/build-push-action@v7
      with:
        context: Packaging/AppImage/docker
        platforms: linux/amd64
        tags: build-vkquake
        load: true
        push: false
        cache-from: type=gha
        cache-to: type=gha
    - name: Build vkQuake
      run: docker run --rm --privileged -e VERSION=${{ steps.version.outputs.version }} -v "$PWD:/usr/src/vkQuake" build-vkquake /usr/src/vkQuake/Packaging/AppImage/run-in-docker.sh
    - name: Upload vkQuake
      uses: actions/upload-artifact@v7
      with:
        name: vkQuake AppImage
        path: Packaging/AppImage/vkQuake-*.AppImage
    - name: Attach to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: Packaging/AppImage/vkQuake-*.AppImage
